# SPDX-License-Identifier: MIT
# Copyright (c) 2023. University of Texas at Austin. All rights reserved.

# SPDX-License-Identifier: MIT
# Copyright (c) 2023 University of Washington

.PHONY: clean all run
all run  clean:
	$(MAKE) -C push $@
	$(MAKE) -C push-pull $@
