// SPDX-License-Identifier: MIT
// Copyright (c) 2023. University of Texas at Austin. All rights reserved.

// SPDX-License-Identifier: MIT
// Copyright (c) 2023 University of Washington

#ifndef RTYPE_MASK
#define RTYPE_MASK 0xfe00707f
#endif
#ifndef ITYPE_MASK
#define ITYPE_MASK 0x0000707f
#endif
#ifndef ETYPE_MASK
#define ETYPE_MASK 0xfff0707f
#endif
#ifndef SHIFTTYPE_MASK
#define SHIFTTYPE_MASK 0x4000707f
#endif
#ifndef STYPE_MASK
#define STYPE_MASK 0x0000707f
#endif
#ifndef BTYPE_MASK
#define BTYPE_MASK 0x0000707f
#endif
#ifndef UTYPE_MASK
#define UTYPE_MASK 0x0000007f
#endif
#ifndef JTYPE_MASK
#define JTYPE_MASK 0x0000007f
#endif
#ifndef R4TYPE_MASK
#define R4TYPE_MASK 0x0600707f
#endif
#ifndef SHIFT64TYPE_MASK
#define SHIFT64TYPE_MASK 0x4000707f
#endif
#ifndef CASTYPE_MASK
#define CASTYPE_MASK 0x0600707f
#endif

// this is used for certain floating point instructions
// like fsqrt, fcvt, fclass, and fmove
#ifndef FTYPE_MASK
#define FTYPE_MASK 0xfff0707f
#endif

#ifndef RTYPE_INSTR_VALUE
#define RTYPE_INSTR_VALUE(opcode, funct3, funct7) ((opcode << 0) | (funct3 << 12) | (funct7 << 25))
#endif

#ifndef ITYPE_INSTR_VALUE
#define ITYPE_INSTR_VALUE(opcode, funct3) ((opcode << 0) | (funct3 << 12))
#endif

#ifndef ETYPE_INSTR_VALUE
#define ETYPE_INSTR_VALUE(opcode, funct3, funct12) \
  ((opcode << 0) | (funct3 << 12) | (funct12 << 20))
#endif

#ifndef STYPE_INSTR_VALUE
#define STYPE_INSTR_VALUE(opcode, funct3) ((opcode << 0) | (funct3 << 12))
#endif

#ifndef BTYPE_INSTR_VALUE
#define BTYPE_INSTR_VALUE(opcode, funct3) ((opcode << 0) | (funct3 << 12))
#endif

#ifndef UTYPE_INSTR_VALUE
#define UTYPE_INSTR_VALUE(opcode) ((opcode << 0))
#endif

#ifndef JTYPE_INSTR_VALUE
#define JTYPE_INSTR_VALUE(opcode) ((opcode << 0))
#endif

#ifndef R4TYPE_INSTR_VALUE
#define R4TYPE_INSTR_VALUE(opcode, funct3, funct2) ((opcode << 0) | (funct2 << 25) | (funct3 << 12))
#endif

#ifndef FTYPE_INSTR_VALUE
#define FTYPE_INSTR_VALUE(opcode, funct3, funct7, ext) \
  ((opcode << 0) | (funct3 << 12) | (funct7 << 25) | (ext << 20))
#endif

#ifndef CASTYPE_INSTR_VALUE
#define CASTYPE_INSTR_VALUE(opcode, funct3, funct2) R4TYPE_INSTR_VALUE(opcode, funct3, funct2)
#endif

/* DEFINSTR(mnemonic, value_under_mask, mask) */

/*********/
/* RV32I */
/*********/
DEFINSTR(LUI, UTYPE_INSTR_VALUE(0x37), UTYPE_MASK)
DEFINSTR(AUIPC, UTYPE_INSTR_VALUE(0x17), UTYPE_MASK)

DEFINSTR(JAL, JTYPE_INSTR_VALUE(0x6f), JTYPE_MASK)
DEFINSTR(JALR, ITYPE_INSTR_VALUE(0x67, 0), ITYPE_MASK)

DEFINSTR(BEQ, BTYPE_INSTR_VALUE(0x63, 0), BTYPE_MASK)
DEFINSTR(BNE, BTYPE_INSTR_VALUE(0x63, 1), BTYPE_MASK)
DEFINSTR(BLT, BTYPE_INSTR_VALUE(0x63, 4), BTYPE_MASK)
DEFINSTR(BGE, BTYPE_INSTR_VALUE(0x63, 5), BTYPE_MASK)
DEFINSTR(BLTU, BTYPE_INSTR_VALUE(0x63, 6), BTYPE_MASK)
DEFINSTR(BGEU, BTYPE_INSTR_VALUE(0x63, 7), BTYPE_MASK)

DEFINSTR(LB, ITYPE_INSTR_VALUE(0x03, 0), ITYPE_MASK)
DEFINSTR(LH, ITYPE_INSTR_VALUE(0x03, 1), ITYPE_MASK)
DEFINSTR(LW, ITYPE_INSTR_VALUE(0x03, 2), ITYPE_MASK)
DEFINSTR(LBU, ITYPE_INSTR_VALUE(0x03, 4), ITYPE_MASK)
DEFINSTR(LHU, ITYPE_INSTR_VALUE(0x03, 5), ITYPE_MASK)

DEFINSTR(SB, STYPE_INSTR_VALUE(0x23, 0), STYPE_MASK)
DEFINSTR(SH, STYPE_INSTR_VALUE(0x23, 1), STYPE_MASK)
DEFINSTR(SW, STYPE_INSTR_VALUE(0x23, 2), STYPE_MASK)

DEFINSTR(ADDI, ITYPE_INSTR_VALUE(0x13, 0), ITYPE_MASK)
DEFINSTR(SLTI, ITYPE_INSTR_VALUE(0x13, 2), ITYPE_MASK)
DEFINSTR(SLTIU, ITYPE_INSTR_VALUE(0x13, 3), ITYPE_MASK)
DEFINSTR(XORI, ITYPE_INSTR_VALUE(0x13, 4), ITYPE_MASK)
DEFINSTR(ORI, ITYPE_INSTR_VALUE(0x13, 6), ITYPE_MASK)
DEFINSTR(ANDI, ITYPE_INSTR_VALUE(0x13, 7), ITYPE_MASK)

// todo address the encoding of SLLI, SRLI, SRAI
// DEFINSTR(SLLI, RTYPE_INSTR_VALUE(0x13, 1, 0), RTYPE_MASK)
// DEFINSTR(SRLI, RTYPE_INSTR_VALUE(0x13, 5, 0), RTYPE_MASK)
// DEFINSTR(SRAI, RTYPE_INSTR_VALUE(0x13, 5, 32), RTYPE_MASK)

DEFINSTR(ADD, RTYPE_INSTR_VALUE(0x33, 0, 0), RTYPE_MASK)
DEFINSTR(SUB, RTYPE_INSTR_VALUE(0x33, 0, 32), RTYPE_MASK)
DEFINSTR(SLL, RTYPE_INSTR_VALUE(0x33, 1, 0), RTYPE_MASK)
DEFINSTR(SLT, RTYPE_INSTR_VALUE(0x33, 2, 0), RTYPE_MASK)
DEFINSTR(SLTU, RTYPE_INSTR_VALUE(0x33, 3, 0), RTYPE_MASK)
DEFINSTR(XOR, RTYPE_INSTR_VALUE(0x33, 4, 0), RTYPE_MASK)
DEFINSTR(SRL, RTYPE_INSTR_VALUE(0x33, 5, 0), RTYPE_MASK)
DEFINSTR(SRA, RTYPE_INSTR_VALUE(0x33, 5, 32), RTYPE_MASK)
DEFINSTR(OR, RTYPE_INSTR_VALUE(0x33, 6, 0), RTYPE_MASK)
DEFINSTR(AND, RTYPE_INSTR_VALUE(0x33, 7, 0), RTYPE_MASK)

DEFINSTR(FENCE, ITYPE_INSTR_VALUE(0x0f, 0), ITYPE_MASK)
DEFINSTR(FENCE_I, ITYPE_INSTR_VALUE(0x0f, 1), ITYPE_MASK)

DEFINSTR(ECALL, ETYPE_INSTR_VALUE(0x73, 0, 0), ETYPE_MASK)
DEFINSTR(EBREAK, ETYPE_INSTR_VALUE(0x73, 0, 1), ETYPE_MASK)
DEFINSTR(MRET, ETYPE_INSTR_VALUE(0x73, 0, 0x302), ETYPE_MASK)

DEFINSTR(CSRRW, ITYPE_INSTR_VALUE(0x73, 1), ITYPE_MASK)
DEFINSTR(CSRRS, ITYPE_INSTR_VALUE(0x73, 2), ITYPE_MASK)
DEFINSTR(CSRRC, ITYPE_INSTR_VALUE(0x73, 3), ITYPE_MASK)
DEFINSTR(CSRRWI, ITYPE_INSTR_VALUE(0x73, 5), ITYPE_MASK)
DEFINSTR(CSRRSI, ITYPE_INSTR_VALUE(0x73, 6), ITYPE_MASK)
DEFINSTR(CSRRCI, ITYPE_INSTR_VALUE(0x73, 7), ITYPE_MASK)

/*********/
/* RV64I */
/*********/
DEFINSTR(LWU, ITYPE_INSTR_VALUE(0x03, 6), ITYPE_MASK)
DEFINSTR(LD, ITYPE_INSTR_VALUE(0x03, 3), ITYPE_MASK)

DEFINSTR(SD, STYPE_INSTR_VALUE(0x23, 3), STYPE_MASK)

DEFINSTR(SLLI, RTYPE_INSTR_VALUE(0x13, 1, 0), SHIFT64TYPE_MASK)
DEFINSTR(SRLI, RTYPE_INSTR_VALUE(0x13, 5, 0), SHIFT64TYPE_MASK)
DEFINSTR(SRAI, RTYPE_INSTR_VALUE(0x13, 5, 32), SHIFT64TYPE_MASK)

DEFINSTR(ADDIW, ITYPE_INSTR_VALUE(0x1b, 0), ITYPE_MASK)
DEFINSTR(SLLIW, RTYPE_INSTR_VALUE(0x1b, 1, 0), RTYPE_MASK)
DEFINSTR(SRLIW, RTYPE_INSTR_VALUE(0x1b, 5, 0), RTYPE_MASK)
DEFINSTR(SRAIW, RTYPE_INSTR_VALUE(0x1b, 5, 32), RTYPE_MASK)

DEFINSTR(ADDW, RTYPE_INSTR_VALUE(0x3b, 0, 0), RTYPE_MASK)
DEFINSTR(SUBW, RTYPE_INSTR_VALUE(0x3b, 0, 32), RTYPE_MASK)
DEFINSTR(SLLW, RTYPE_INSTR_VALUE(0x3b, 1, 0), RTYPE_MASK)
DEFINSTR(SRLW, RTYPE_INSTR_VALUE(0x3b, 5, 0), RTYPE_MASK)
DEFINSTR(SRAW, RTYPE_INSTR_VALUE(0x3b, 5, 32), RTYPE_MASK)

/*********/
/* RV32M */
/*********/
DEFINSTR(MUL, RTYPE_INSTR_VALUE(0x33, 0, 1), RTYPE_MASK)
DEFINSTR(MULH, RTYPE_INSTR_VALUE(0x33, 1, 1), RTYPE_MASK)
DEFINSTR(MULHSU, RTYPE_INSTR_VALUE(0x33, 2, 1), RTYPE_MASK)
DEFINSTR(MULHU, RTYPE_INSTR_VALUE(0x33, 3, 1), RTYPE_MASK)
DEFINSTR(DIV, RTYPE_INSTR_VALUE(0x33, 4, 1), RTYPE_MASK)
DEFINSTR(DIVU, RTYPE_INSTR_VALUE(0x33, 5, 1), RTYPE_MASK)
DEFINSTR(REM, RTYPE_INSTR_VALUE(0x33, 6, 1), RTYPE_MASK)
DEFINSTR(REMU, RTYPE_INSTR_VALUE(0x33, 7, 1), RTYPE_MASK)

/*********/
/* RV64M */
/*********/
DEFINSTR(MULW, RTYPE_INSTR_VALUE(0x3b, 0, 1), RTYPE_MASK)
DEFINSTR(DIVW, RTYPE_INSTR_VALUE(0x3b, 4, 1), RTYPE_MASK)
DEFINSTR(DIVUW, RTYPE_INSTR_VALUE(0x3b, 5, 1), RTYPE_MASK)
DEFINSTR(REMW, RTYPE_INSTR_VALUE(0x3b, 6, 1), RTYPE_MASK)
DEFINSTR(REMUW, RTYPE_INSTR_VALUE(0x3b, 7, 1), RTYPE_MASK)

/*********/
/* RV32A */
/*********/
DEFINSTR(LRW, RTYPE_INSTR_VALUE(0x2f, 2, 8), RTYPE_MASK)
DEFINSTR(LRW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 9), RTYPE_MASK)
DEFINSTR(LRW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 10), RTYPE_MASK)
DEFINSTR(LRW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 11), RTYPE_MASK)

DEFINSTR(SCW, RTYPE_INSTR_VALUE(0x2f, 2, 12), RTYPE_MASK)
DEFINSTR(SCW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 13), RTYPE_MASK)
DEFINSTR(SCW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 14), RTYPE_MASK)
DEFINSTR(SCW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 15), RTYPE_MASK)

DEFINSTR(AMOSWAPW, RTYPE_INSTR_VALUE(0x2f, 2, 4), RTYPE_MASK)
DEFINSTR(AMOSWAPW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 5), RTYPE_MASK)
DEFINSTR(AMOSWAPW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 6), RTYPE_MASK)
DEFINSTR(AMOSWAPW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 7), RTYPE_MASK)

DEFINSTR(AMOADDW, RTYPE_INSTR_VALUE(0x2f, 2, 0), RTYPE_MASK)
DEFINSTR(AMOADDW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 1), RTYPE_MASK)
DEFINSTR(AMOADDW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 2), RTYPE_MASK)
DEFINSTR(AMOADDW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 3), RTYPE_MASK)

DEFINSTR(AMOXORW, RTYPE_INSTR_VALUE(0x2f, 2, 16), RTYPE_MASK)
DEFINSTR(AMOXORW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 17), RTYPE_MASK)
DEFINSTR(AMOXORW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 18), RTYPE_MASK)
DEFINSTR(AMOXORW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 19), RTYPE_MASK)

DEFINSTR(AMOANDW, RTYPE_INSTR_VALUE(0x2f, 2, 48), RTYPE_MASK)
DEFINSTR(AMOANDW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 49), RTYPE_MASK)
DEFINSTR(AMOANDW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 50), RTYPE_MASK)
DEFINSTR(AMOANDW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 51), RTYPE_MASK)

DEFINSTR(AMOORW, RTYPE_INSTR_VALUE(0x2f, 2, 32), RTYPE_MASK)
DEFINSTR(AMOORW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 33), RTYPE_MASK)
DEFINSTR(AMOORW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 34), RTYPE_MASK)
DEFINSTR(AMOORW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 35), RTYPE_MASK)

DEFINSTR(AMOMINW, RTYPE_INSTR_VALUE(0x2f, 2, 64), RTYPE_MASK)
DEFINSTR(AMOMINW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 65), RTYPE_MASK)
DEFINSTR(AMOMINW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 66), RTYPE_MASK)
DEFINSTR(AMOMINW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 67), RTYPE_MASK)

DEFINSTR(AMOMAXW, RTYPE_INSTR_VALUE(0x2f, 2, 80), RTYPE_MASK)
DEFINSTR(AMOMAXW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 81), RTYPE_MASK)
DEFINSTR(AMOMAXW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 82), RTYPE_MASK)
DEFINSTR(AMOMAXW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 83), RTYPE_MASK)

DEFINSTR(AMOMINUW, RTYPE_INSTR_VALUE(0x2f, 2, 96), RTYPE_MASK)
DEFINSTR(AMOMINUW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 97), RTYPE_MASK)
DEFINSTR(AMOMINUW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 98), RTYPE_MASK)
DEFINSTR(AMOMINUW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 99), RTYPE_MASK)

DEFINSTR(AMOMAXUW, RTYPE_INSTR_VALUE(0x2f, 2, 112), RTYPE_MASK)
DEFINSTR(AMOMAXUW_RL, RTYPE_INSTR_VALUE(0x2f, 2, 113), RTYPE_MASK)
DEFINSTR(AMOMAXUW_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 114), RTYPE_MASK)
DEFINSTR(AMOMAXUW_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 2, 115), RTYPE_MASK)

/**************************************************************************************************/
/* https://docs.google.com/spreadsheets/d/1dSmdTiol_tSbBjMDvYSLObbvGzXWACW3kSGsRaqjt7Q/edit#gid=0 */
/**************************************************************************************************/
DEFINSTR(AMOCASW, CASTYPE_INSTR_VALUE(0x2b, 2, 0), CASTYPE_MASK)
DEFINSTR(AMOCASW_RL, CASTYPE_INSTR_VALUE(0x2b, 2, 1), CASTYPE_MASK)
DEFINSTR(AMOCASW_AQ, CASTYPE_INSTR_VALUE(0x2b, 2, 2), CASTYPE_MASK)
DEFINSTR(AMOCASW_RL_AQ, CASTYPE_INSTR_VALUE(0x2b, 2, 3), CASTYPE_MASK)

/*********/
/* RV64A */
/*********/
DEFINSTR(LRD, RTYPE_INSTR_VALUE(0x2f, 3, 8), RTYPE_MASK)
DEFINSTR(LRD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 9), RTYPE_MASK)
DEFINSTR(LRD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 10), RTYPE_MASK)
DEFINSTR(LRD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 11), RTYPE_MASK)

DEFINSTR(SCD, RTYPE_INSTR_VALUE(0x2f, 3, 12), RTYPE_MASK)
DEFINSTR(SCD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 13), RTYPE_MASK)
DEFINSTR(SCD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 14), RTYPE_MASK)
DEFINSTR(SCD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 15), RTYPE_MASK)

DEFINSTR(AMOSWAPD, RTYPE_INSTR_VALUE(0x2f, 3, 4), RTYPE_MASK)
DEFINSTR(AMOSWAPD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 5), RTYPE_MASK)
DEFINSTR(AMOSWAPD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 6), RTYPE_MASK)
DEFINSTR(AMOSWAPD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 7), RTYPE_MASK)

DEFINSTR(AMOADDD, RTYPE_INSTR_VALUE(0x2f, 3, 0), RTYPE_MASK)
DEFINSTR(AMOADDD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 1), RTYPE_MASK)
DEFINSTR(AMOADDD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 2), RTYPE_MASK)
DEFINSTR(AMOADDD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 3), RTYPE_MASK)

DEFINSTR(AMOXORD, RTYPE_INSTR_VALUE(0x2f, 3, 16), RTYPE_MASK)
DEFINSTR(AMOXORD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 17), RTYPE_MASK)
DEFINSTR(AMOXORD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 18), RTYPE_MASK)
DEFINSTR(AMOXORD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 19), RTYPE_MASK)

DEFINSTR(AMOANDD, RTYPE_INSTR_VALUE(0x2f, 3, 48), RTYPE_MASK)
DEFINSTR(AMOANDD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 49), RTYPE_MASK)
DEFINSTR(AMOANDD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 50), RTYPE_MASK)
DEFINSTR(AMOANDD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 51), RTYPE_MASK)

DEFINSTR(AMOORD, RTYPE_INSTR_VALUE(0x2f, 3, 32), RTYPE_MASK)
DEFINSTR(AMOORD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 33), RTYPE_MASK)
DEFINSTR(AMOORD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 34), RTYPE_MASK)
DEFINSTR(AMOORD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 35), RTYPE_MASK)

DEFINSTR(AMOMIND, RTYPE_INSTR_VALUE(0x2f, 3, 64), RTYPE_MASK)
DEFINSTR(AMOMIND_RL, RTYPE_INSTR_VALUE(0x2f, 3, 65), RTYPE_MASK)
DEFINSTR(AMOMIND_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 66), RTYPE_MASK)
DEFINSTR(AMOMIND_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 67), RTYPE_MASK)

DEFINSTR(AMOMAXD, RTYPE_INSTR_VALUE(0x2f, 3, 80), RTYPE_MASK)
DEFINSTR(AMOMAXD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 81), RTYPE_MASK)
DEFINSTR(AMOMAXD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 82), RTYPE_MASK)
DEFINSTR(AMOMAXD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 83), RTYPE_MASK)

DEFINSTR(AMOMINUD, RTYPE_INSTR_VALUE(0x2f, 3, 96), RTYPE_MASK)
DEFINSTR(AMOMINUD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 97), RTYPE_MASK)
DEFINSTR(AMOMINUD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 98), RTYPE_MASK)
DEFINSTR(AMOMINUD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 99), RTYPE_MASK)

DEFINSTR(AMOMAXUD, RTYPE_INSTR_VALUE(0x2f, 3, 112), RTYPE_MASK)
DEFINSTR(AMOMAXUD_RL, RTYPE_INSTR_VALUE(0x2f, 3, 113), RTYPE_MASK)
DEFINSTR(AMOMAXUD_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 114), RTYPE_MASK)
DEFINSTR(AMOMAXUD_RL_AQ, RTYPE_INSTR_VALUE(0x2f, 3, 115), RTYPE_MASK)

/**************************************************************************************************/
/* https://docs.google.com/spreadsheets/d/1dSmdTiol_tSbBjMDvYSLObbvGzXWACW3kSGsRaqjt7Q/edit#gid=0 */
/**************************************************************************************************/
DEFINSTR(AMOCASD, CASTYPE_INSTR_VALUE(0x2b, 3, 0), CASTYPE_MASK)
DEFINSTR(AMOCASD_RL, CASTYPE_INSTR_VALUE(0x2b, 3, 1), CASTYPE_MASK)
DEFINSTR(AMOCASD_AQ, CASTYPE_INSTR_VALUE(0x2b, 3, 2), CASTYPE_MASK)
DEFINSTR(AMOCASD_RL_AQ, CASTYPE_INSTR_VALUE(0x2b, 3, 3), CASTYPE_MASK)

/*********/
/* RV32F */
/*********/
#define FP_RNE 0
#define FP_RTZ 1
#define FP_RDN 2
#define FP_RUP 3
#define FP_RMM 4
#define FP_DYN 7

DEFINSTR(FLW, ITYPE_INSTR_VALUE(0x07, 2), ITYPE_MASK)
DEFINSTR(FSW, STYPE_INSTR_VALUE(0x27, 2), STYPE_MASK)

DEFINSTR(FMADD_S_RNE, R4TYPE_INSTR_VALUE(0x43, FP_RNE, 0), R4TYPE_MASK)
DEFINSTR(FMADD_S_RTZ, R4TYPE_INSTR_VALUE(0x43, FP_RTZ, 0), R4TYPE_MASK)
DEFINSTR(FMADD_S_RDN, R4TYPE_INSTR_VALUE(0x43, FP_RDN, 0), R4TYPE_MASK)
DEFINSTR(FMADD_S_RUP, R4TYPE_INSTR_VALUE(0x43, FP_RUP, 0), R4TYPE_MASK)
DEFINSTR(FMADD_S_RMM, R4TYPE_INSTR_VALUE(0x43, FP_RMM, 0), R4TYPE_MASK)
DEFINSTR(FMADD_S_DYN, R4TYPE_INSTR_VALUE(0x43, FP_DYN, 0), R4TYPE_MASK)

DEFINSTR(FMSUB_S_RNE, R4TYPE_INSTR_VALUE(0x47, FP_RNE, 0), R4TYPE_MASK)
DEFINSTR(FMSUB_S_RTZ, R4TYPE_INSTR_VALUE(0x47, FP_RTZ, 0), R4TYPE_MASK)
DEFINSTR(FMSUB_S_RDN, R4TYPE_INSTR_VALUE(0x47, FP_RDN, 0), R4TYPE_MASK)
DEFINSTR(FMSUB_S_RUP, R4TYPE_INSTR_VALUE(0x47, FP_RUP, 0), R4TYPE_MASK)
DEFINSTR(FMSUB_S_RMM, R4TYPE_INSTR_VALUE(0x47, FP_RMM, 0), R4TYPE_MASK)
DEFINSTR(FMSUB_S_DYN, R4TYPE_INSTR_VALUE(0x47, FP_DYN, 0), R4TYPE_MASK)

DEFINSTR(FNMSUB_S_RNE, R4TYPE_INSTR_VALUE(0x4b, FP_RNE, 0), R4TYPE_MASK)
DEFINSTR(FNMSUB_S_RTZ, R4TYPE_INSTR_VALUE(0x4b, FP_RTZ, 0), R4TYPE_MASK)
DEFINSTR(FNMSUB_S_RDN, R4TYPE_INSTR_VALUE(0x4b, FP_RDN, 0), R4TYPE_MASK)
DEFINSTR(FNMSUB_S_RUP, R4TYPE_INSTR_VALUE(0x4b, FP_RUP, 0), R4TYPE_MASK)
DEFINSTR(FNMSUB_S_RMM, R4TYPE_INSTR_VALUE(0x4b, FP_RMM, 0), R4TYPE_MASK)
DEFINSTR(FNMSUB_S_DYN, R4TYPE_INSTR_VALUE(0x4b, FP_DYN, 0), R4TYPE_MASK)

DEFINSTR(FNMADD_S_RNE, R4TYPE_INSTR_VALUE(0x4f, FP_RNE, 0), R4TYPE_MASK)
DEFINSTR(FNMADD_S_RTZ, R4TYPE_INSTR_VALUE(0x4f, FP_RTZ, 0), R4TYPE_MASK)
DEFINSTR(FNMADD_S_RDN, R4TYPE_INSTR_VALUE(0x4f, FP_RDN, 0), R4TYPE_MASK)
DEFINSTR(FNMADD_S_RUP, R4TYPE_INSTR_VALUE(0x4f, FP_RUP, 0), R4TYPE_MASK)
DEFINSTR(FNMADD_S_RMM, R4TYPE_INSTR_VALUE(0x4f, FP_RMM, 0), R4TYPE_MASK)
DEFINSTR(FNMADD_S_DYN, R4TYPE_INSTR_VALUE(0x4f, FP_DYN, 0), R4TYPE_MASK)

DEFINSTR(FADD_S_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 0), RTYPE_MASK)
DEFINSTR(FADD_S_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 0), RTYPE_MASK)
DEFINSTR(FADD_S_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 0), RTYPE_MASK)
DEFINSTR(FADD_S_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 0), RTYPE_MASK)
DEFINSTR(FADD_S_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 0), RTYPE_MASK)
DEFINSTR(FADD_S_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 0), RTYPE_MASK)

DEFINSTR(FSUB_S_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 4), RTYPE_MASK)
DEFINSTR(FSUB_S_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 4), RTYPE_MASK)
DEFINSTR(FSUB_S_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 4), RTYPE_MASK)
DEFINSTR(FSUB_S_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 4), RTYPE_MASK)
DEFINSTR(FSUB_S_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 4), RTYPE_MASK)
DEFINSTR(FSUB_S_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 4), RTYPE_MASK)

DEFINSTR(FMUL_S_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 8), RTYPE_MASK)
DEFINSTR(FMUL_S_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 8), RTYPE_MASK)
DEFINSTR(FMUL_S_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 8), RTYPE_MASK)
DEFINSTR(FMUL_S_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 8), RTYPE_MASK)
DEFINSTR(FMUL_S_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 8), RTYPE_MASK)
DEFINSTR(FMUL_S_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 8), RTYPE_MASK)

DEFINSTR(FDIV_S_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 12), RTYPE_MASK)
DEFINSTR(FDIV_S_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 12), RTYPE_MASK)
DEFINSTR(FDIV_S_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 12), RTYPE_MASK)
DEFINSTR(FDIV_S_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 12), RTYPE_MASK)
DEFINSTR(FDIV_S_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 12), RTYPE_MASK)
DEFINSTR(FDIV_S_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 12), RTYPE_MASK)

DEFINSTR(FSQRT_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 44, 0), FTYPE_MASK)
DEFINSTR(FSQRT_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 44, 0), FTYPE_MASK)
DEFINSTR(FSQRT_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 44, 0), FTYPE_MASK)
DEFINSTR(FSQRT_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 44, 0), FTYPE_MASK)
DEFINSTR(FSQRT_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 44, 0), FTYPE_MASK)
DEFINSTR(FSQRT_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 44, 0), FTYPE_MASK)

DEFINSTR(FSGNJ_S, RTYPE_INSTR_VALUE(0x53, 0, 16), RTYPE_MASK)
DEFINSTR(FSGNJN_S, RTYPE_INSTR_VALUE(0x53, 1, 16), RTYPE_MASK)
DEFINSTR(FSGNJX_S, RTYPE_INSTR_VALUE(0x53, 2, 16), RTYPE_MASK)

DEFINSTR(FMIN_S, RTYPE_INSTR_VALUE(0x53, 0, 20), RTYPE_MASK)
DEFINSTR(FMAX_S, RTYPE_INSTR_VALUE(0x53, 1, 20), RTYPE_MASK)

DEFINSTR(FCVT_W_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 96, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 96, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 96, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 96, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 96, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 96, 0), FTYPE_MASK)

DEFINSTR(FCVT_WU_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 96, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 96, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 96, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 96, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 96, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 96, 1), FTYPE_MASK)

DEFINSTR(FMV_X_W, FTYPE_INSTR_VALUE(0x53, 0, 112, 0), FTYPE_MASK)
DEFINSTR(FEQ_S, RTYPE_INSTR_VALUE(0x53, 2, 80), RTYPE_MASK)
DEFINSTR(FLE_S, RTYPE_INSTR_VALUE(0x53, 1, 80), RTYPE_MASK)
DEFINSTR(FLT_S, RTYPE_INSTR_VALUE(0x53, 0, 80), RTYPE_MASK)

DEFINSTR(FCLASS_S, FTYPE_INSTR_VALUE(0x53, 1, 112, 0), FTYPE_MASK)

DEFINSTR(FCVT_S_W_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 104, 0), FTYPE_MASK)
DEFINSTR(FCVT_S_W_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 104, 0), FTYPE_MASK)
DEFINSTR(FCVT_S_W_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 104, 0), FTYPE_MASK)
DEFINSTR(FCVT_S_W_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 104, 0), FTYPE_MASK)
DEFINSTR(FCVT_S_W_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 104, 0), FTYPE_MASK)
DEFINSTR(FCVT_S_W_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 104, 0), FTYPE_MASK)

DEFINSTR(FCVT_S_WU_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 104, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_WU_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 104, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_WU_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 104, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_WU_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 104, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_WU_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 104, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_WU_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 104, 1), FTYPE_MASK)

DEFINSTR(FMV_W_X, FTYPE_INSTR_VALUE(0x53, 0, 120, 0), FTYPE_MASK)

/*********/
/* RV64F */
/*********/
DEFINSTR(FCVT_L_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 96, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 96, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 96, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 96, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 96, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 96, 2), FTYPE_MASK)

DEFINSTR(FCVT_LU_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 96, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 96, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 96, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 96, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 96, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 96, 3), FTYPE_MASK)

DEFINSTR(FCVT_S_L_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 104, 2), FTYPE_MASK)
DEFINSTR(FCVT_S_L_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 104, 2), FTYPE_MASK)
DEFINSTR(FCVT_S_L_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 104, 2), FTYPE_MASK)
DEFINSTR(FCVT_S_L_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 104, 2), FTYPE_MASK)
DEFINSTR(FCVT_S_L_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 104, 2), FTYPE_MASK)
DEFINSTR(FCVT_S_L_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 104, 2), FTYPE_MASK)

DEFINSTR(FCVT_S_LU_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 104, 3), FTYPE_MASK)
DEFINSTR(FCVT_S_LU_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 104, 3), FTYPE_MASK)
DEFINSTR(FCVT_S_LU_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 104, 3), FTYPE_MASK)
DEFINSTR(FCVT_S_LU_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 104, 3), FTYPE_MASK)
DEFINSTR(FCVT_S_LU_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 104, 3), FTYPE_MASK)
DEFINSTR(FCVT_S_LU_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 104, 3), FTYPE_MASK)

/*********/
/* RV32D */
/*********/
DEFINSTR(FLD, ITYPE_INSTR_VALUE(0x07, 3), ITYPE_MASK)
DEFINSTR(FSD, STYPE_INSTR_VALUE(0x27, 3), STYPE_MASK)

DEFINSTR(FMADD_D_RNE, R4TYPE_INSTR_VALUE(0x43, FP_RNE, 1), R4TYPE_MASK)
DEFINSTR(FMADD_D_RTZ, R4TYPE_INSTR_VALUE(0x43, FP_RTZ, 1), R4TYPE_MASK)
DEFINSTR(FMADD_D_RDN, R4TYPE_INSTR_VALUE(0x43, FP_RDN, 1), R4TYPE_MASK)
DEFINSTR(FMADD_D_RUP, R4TYPE_INSTR_VALUE(0x43, FP_RUP, 1), R4TYPE_MASK)
DEFINSTR(FMADD_D_RMM, R4TYPE_INSTR_VALUE(0x43, FP_RMM, 1), R4TYPE_MASK)
DEFINSTR(FMADD_D_DYN, R4TYPE_INSTR_VALUE(0x43, FP_DYN, 1), R4TYPE_MASK)

DEFINSTR(FMSUB_D_RNE, R4TYPE_INSTR_VALUE(0x47, FP_RNE, 1), R4TYPE_MASK)
DEFINSTR(FMSUB_D_RTZ, R4TYPE_INSTR_VALUE(0x47, FP_RTZ, 1), R4TYPE_MASK)
DEFINSTR(FMSUB_D_RDN, R4TYPE_INSTR_VALUE(0x47, FP_RDN, 1), R4TYPE_MASK)
DEFINSTR(FMSUB_D_RUP, R4TYPE_INSTR_VALUE(0x47, FP_RUP, 1), R4TYPE_MASK)
DEFINSTR(FMSUB_D_RMM, R4TYPE_INSTR_VALUE(0x47, FP_RMM, 1), R4TYPE_MASK)
DEFINSTR(FMSUB_D_DYN, R4TYPE_INSTR_VALUE(0x47, FP_DYN, 1), R4TYPE_MASK)

DEFINSTR(FNMSUB_D_RNE, R4TYPE_INSTR_VALUE(0x4b, FP_RNE, 1), R4TYPE_MASK)
DEFINSTR(FNMSUB_D_RTZ, R4TYPE_INSTR_VALUE(0x4b, FP_RTZ, 1), R4TYPE_MASK)
DEFINSTR(FNMSUB_D_RDN, R4TYPE_INSTR_VALUE(0x4b, FP_RDN, 1), R4TYPE_MASK)
DEFINSTR(FNMSUB_D_RUP, R4TYPE_INSTR_VALUE(0x4b, FP_RUP, 1), R4TYPE_MASK)
DEFINSTR(FNMSUB_D_RMM, R4TYPE_INSTR_VALUE(0x4b, FP_RMM, 1), R4TYPE_MASK)
DEFINSTR(FNMSUB_D_DYN, R4TYPE_INSTR_VALUE(0x4b, FP_DYN, 1), R4TYPE_MASK)

DEFINSTR(FNMADD_D_RNE, R4TYPE_INSTR_VALUE(0x4f, FP_RNE, 1), R4TYPE_MASK)
DEFINSTR(FNMADD_D_RTZ, R4TYPE_INSTR_VALUE(0x4f, FP_RTZ, 1), R4TYPE_MASK)
DEFINSTR(FNMADD_D_RDN, R4TYPE_INSTR_VALUE(0x4f, FP_RDN, 1), R4TYPE_MASK)
DEFINSTR(FNMADD_D_RUP, R4TYPE_INSTR_VALUE(0x4f, FP_RUP, 1), R4TYPE_MASK)
DEFINSTR(FNMADD_D_RMM, R4TYPE_INSTR_VALUE(0x4f, FP_RMM, 1), R4TYPE_MASK)
DEFINSTR(FNMADD_D_DYN, R4TYPE_INSTR_VALUE(0x4f, FP_DYN, 1), R4TYPE_MASK)

DEFINSTR(FADD_D_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 1), RTYPE_MASK)
DEFINSTR(FADD_D_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 1), RTYPE_MASK)
DEFINSTR(FADD_D_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 1), RTYPE_MASK)
DEFINSTR(FADD_D_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 1), RTYPE_MASK)
DEFINSTR(FADD_D_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 1), RTYPE_MASK)
DEFINSTR(FADD_D_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 1), RTYPE_MASK)

DEFINSTR(FSUB_D_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 5), RTYPE_MASK)
DEFINSTR(FSUB_D_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 5), RTYPE_MASK)
DEFINSTR(FSUB_D_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 5), RTYPE_MASK)
DEFINSTR(FSUB_D_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 5), RTYPE_MASK)
DEFINSTR(FSUB_D_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 5), RTYPE_MASK)
DEFINSTR(FSUB_D_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 5), RTYPE_MASK)

DEFINSTR(FMUL_D_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 2), RTYPE_MASK)
DEFINSTR(FMUL_D_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 2), RTYPE_MASK)
DEFINSTR(FMUL_D_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 2), RTYPE_MASK)
DEFINSTR(FMUL_D_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 2), RTYPE_MASK)
DEFINSTR(FMUL_D_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 2), RTYPE_MASK)
DEFINSTR(FMUL_D_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 2), RTYPE_MASK)

DEFINSTR(FDIV_D_RNE, RTYPE_INSTR_VALUE(0x53, FP_RNE, 6), RTYPE_MASK)
DEFINSTR(FDIV_D_RTZ, RTYPE_INSTR_VALUE(0x53, FP_RTZ, 6), RTYPE_MASK)
DEFINSTR(FDIV_D_RDN, RTYPE_INSTR_VALUE(0x53, FP_RDN, 6), RTYPE_MASK)
DEFINSTR(FDIV_D_RUP, RTYPE_INSTR_VALUE(0x53, FP_RUP, 6), RTYPE_MASK)
DEFINSTR(FDIV_D_RMM, RTYPE_INSTR_VALUE(0x53, FP_RMM, 6), RTYPE_MASK)
DEFINSTR(FDIV_D_DYN, RTYPE_INSTR_VALUE(0x53, FP_DYN, 6), RTYPE_MASK)

DEFINSTR(FSQRT_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 7, 45), FTYPE_MASK)
DEFINSTR(FSQRT_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 7, 45), FTYPE_MASK)
DEFINSTR(FSQRT_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 7, 45), FTYPE_MASK)
DEFINSTR(FSQRT_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 7, 45), FTYPE_MASK)
DEFINSTR(FSQRT_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 7, 45), FTYPE_MASK)
DEFINSTR(FSQRT_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 7, 45), FTYPE_MASK)

DEFINSTR(FSGNJ_D, RTYPE_INSTR_VALUE(0x53, 0, 17), RTYPE_MASK)
DEFINSTR(FSGNJN_D, RTYPE_INSTR_VALUE(0x53, 1, 17), RTYPE_MASK)
DEFINSTR(FSGNJX_D, RTYPE_INSTR_VALUE(0x53, 2, 17), RTYPE_MASK)

DEFINSTR(FMIN_D, RTYPE_INSTR_VALUE(0x53, 0, 21), RTYPE_MASK)
DEFINSTR(FMAX_D, RTYPE_INSTR_VALUE(0x53, 1, 21), RTYPE_MASK)

DEFINSTR(FCVT_S_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 32, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 32, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 32, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 32, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 32, 1), FTYPE_MASK)
DEFINSTR(FCVT_S_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 32, 1), FTYPE_MASK)

DEFINSTR(FCVT_D_S_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 33, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_S_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 33, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_S_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 33, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_S_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 33, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_S_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 33, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_S_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 33, 1), FTYPE_MASK)

DEFINSTR(FEQ_D, RTYPE_INSTR_VALUE(0x53, 2, 81), RTYPE_MASK)
DEFINSTR(FLE_D, RTYPE_INSTR_VALUE(0x53, 1, 81), RTYPE_MASK)
DEFINSTR(FLT_D, RTYPE_INSTR_VALUE(0x53, 0, 81), RTYPE_MASK)

DEFINSTR(FCLASS_D, FTYPE_INSTR_VALUE(0x53, 1, 113, 0), FTYPE_MASK)

DEFINSTR(FCVT_W_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 97, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 97, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 97, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 97, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 97, 0), FTYPE_MASK)
DEFINSTR(FCVT_W_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 97, 0), FTYPE_MASK)

DEFINSTR(FCVT_WU_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 97, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 97, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 97, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 97, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 97, 1), FTYPE_MASK)
DEFINSTR(FCVT_WU_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 97, 1), FTYPE_MASK)

DEFINSTR(FCVT_D_W_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 105, 0), FTYPE_MASK)
DEFINSTR(FCVT_D_W_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 105, 0), FTYPE_MASK)
DEFINSTR(FCVT_D_W_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 105, 0), FTYPE_MASK)
DEFINSTR(FCVT_D_W_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 105, 0), FTYPE_MASK)
DEFINSTR(FCVT_D_W_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 105, 0), FTYPE_MASK)
DEFINSTR(FCVT_D_W_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 105, 0), FTYPE_MASK)

DEFINSTR(FCVT_D_WU_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 105, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_WU_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 105, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_WU_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 105, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_WU_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 105, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_WU_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 105, 1), FTYPE_MASK)
DEFINSTR(FCVT_D_WU_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 105, 1), FTYPE_MASK)

/***********/
/* RV64D   */
/***********/
DEFINSTR(FCVT_L_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 97, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 97, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 97, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 97, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 97, 2), FTYPE_MASK)
DEFINSTR(FCVT_L_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 97, 2), FTYPE_MASK)

DEFINSTR(FCVT_LU_D_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 97, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_D_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 97, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_D_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 97, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_D_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 97, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_D_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 97, 3), FTYPE_MASK)
DEFINSTR(FCVT_LU_D_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 97, 3), FTYPE_MASK)

DEFINSTR(FMV_X_D, FTYPE_INSTR_VALUE(0x53, 0, 113, 0), FTYPE_MASK)

DEFINSTR(FCVT_D_L_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 105, 2), FTYPE_MASK)
DEFINSTR(FCVT_D_L_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 105, 2), FTYPE_MASK)
DEFINSTR(FCVT_D_L_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 105, 2), FTYPE_MASK)
DEFINSTR(FCVT_D_L_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 105, 2), FTYPE_MASK)
DEFINSTR(FCVT_D_L_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 105, 2), FTYPE_MASK)
DEFINSTR(FCVT_D_L_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 105, 2), FTYPE_MASK)

DEFINSTR(FCVT_D_LU_RNE, FTYPE_INSTR_VALUE(0x53, FP_RNE, 105, 3), FTYPE_MASK)
DEFINSTR(FCVT_D_LU_RTZ, FTYPE_INSTR_VALUE(0x53, FP_RTZ, 105, 3), FTYPE_MASK)
DEFINSTR(FCVT_D_LU_RDN, FTYPE_INSTR_VALUE(0x53, FP_RDN, 105, 3), FTYPE_MASK)
DEFINSTR(FCVT_D_LU_RUP, FTYPE_INSTR_VALUE(0x53, FP_RUP, 105, 3), FTYPE_MASK)
DEFINSTR(FCVT_D_LU_RMM, FTYPE_INSTR_VALUE(0x53, FP_RMM, 105, 3), FTYPE_MASK)
DEFINSTR(FCVT_D_LU_DYN, FTYPE_INSTR_VALUE(0x53, FP_DYN, 105, 3), FTYPE_MASK)

DEFINSTR(FMV_D_X, FTYPE_INSTR_VALUE(0x53, 0, 121, 0), FTYPE_MASK)
