# SPDX-License-Identifier: MIT
# Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.

DRV_DIR := $(shell git rev-parse --show-toplevel)
TARGET := exe.riscv
RISCV_CXXSOURCE := $(wildcard *.cpp)
include $(DRV_DIR)/mk/riscv_common.mk
