# SPDX-License-Identifier: MIT
# Copyright (c) 2023. University of Texas at Austin. All rights reserved.

# SPDX-License-Identifier: MIT

TARGET=binaryArr

$(TARGET) : $(TARGET).cc $(TARGET).h
	g++ --std=c++17 $(TARGET).cc -o $(TARGET)
