# SPDX-License-Identifier: MIT
# Copyright (c) 2023. University of Texas at Austin. All rights reserved.

# SPDX-License-Identifier: MIT
# Copyright (c) 2023 University of Washington

import sys

script_fmt = """#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2023 University of Washington
#
# This script is generated by make-drv-compile-flags.py
echo {}
"""

print(script_fmt.format(" ".join(sys.argv[1:])))
