// SPDX-License-Identifier: MIT
// Copyright (c) 2023 University of Washington

        .global _start
_start:
        li      x1, 1
        li      x2, 2
        li      x3, 3
        li      x4, 4
        li      x5, 5
        li      x6, 6
        li      x7, 7
        li      x8, 8
        li      x9, 9
        li      x10, 0
        li      x11, 0
        li      x12, 0
        li      x13, 0
        li      x14, 0
        li      x15, 0
        li      x16, 0
        li      x17, 0
        li      x18, 0
        li      x19, 0
        li      x20, 0
        li      x21, 0
        li      x22, 0
        li      x23, 0
        li      x24, 0
        li      x25, 0
        li      x26, 0
        li      x27, 0
        li      x28, 0
        li      x29, 0
        li      x30, 0
        li      x31, 0
done:
        j done
